apiVersion: apps/v1
kind: Deployment
metadata:
  name: oskiu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oskiu
  template:
    metadata:
      labels:
        app: oskiu
    spec:
      containers:
      - image: okteto.dev/oskiu:latest
        name: oskiu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b8e1488a-7e00-42dd-ab05-7e6b23f5e140"
        - name: Vless_Path
          value: "/vl181818"
        - name: Vmess_UUID
          value: "b8e1488a-7e00-42dd-ab05-7e6b23f5e140"
        - name: Vmess_Path
          value: "/vm181818"
        - name: Share_Path
          value: "/v2link"
